#!/bin/bash

# Stubs out git for tests. This way we can verify the right commands are
# being run without actually cloning or changing versions. Writing tests
# otherwise is tricky because you're testing the cloned toolkit instead
# of the local one.
echo "$@" >> git-input
[ "$1" = clone ] && {
  mkdir -p .rax-docs/repo/internal
  mv main .rax-docs/repo/internal
}
exit 0
