#!/bin/bash

# Stubs out docker for tests. This way we can verify the right
# commands are being run without worrying about whether the image
# exists, waiting for it to be built, etc.

echo "$@" >> docker-input
exit 0
